### ISSUE TITLE
3d Scanner Software 

### ISSUE THREAD

**Issue by Paerhugo** [Open-Lab-Starter-Kit/OLSK-3D-Scanner#1]
Hello, i want to use you 3d scanner. In Motion Lab Berlin. 

I want to install the software here on my computer. Its a MAC. 
I downloaded: Software/V3/Laptop_side but the folder 3d scanner is empty. 

Where can i find it? 

@satshas 

Thanks / Pär

**Comment by mhdsulaimantan** [comment]
Hi @Paerhugo,

I pushed the source code now. you can find it again in the same directory.
